Bpf 1645
TFG-Labs/order-placed pull request #12
Opened 2023-09-13 06:37 UTC by harlyon

#### What is the purpose of this pull request?
https://tfginfotec.atlassian.net/browse/BPF-1645

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2023-09-13 06:54 UTC, simmbiote requested changes

2023-09-13 06:54 UTC, simmbiote commented on react/FurnitureNote.tsx
> +      <a href="#/customer-service/help" className={handles.noteLink}>
Is this link correct? Shouldn't it be somewhere on help.bash.com?

2023-09-13 06:54 UTC, simmbiote commented on react/ConfirmationMessage.tsx
> +                  {orderGroup.orders[0].clientProfileData.phone}
This could be undefined

2023-09-13 06:54 UTC, simmbiote commented on react/ConfirmationMessage.tsx
> +    orderGroup.orders[0].pickUpParcels.length > 0 ? 'collect' : 'deliver'
Is there risk of pickUpParcels being undefined?

2023-09-13 06:55 UTC, harlyon commented on react/ConfirmationMessage.tsx
> +    orderGroup.orders[0].pickUpParcels.length > 0 ? 'collect' : 'deliver'
@simmbiote these are not my changes oops

2023-09-13 07:06 UTC, simmbiote approved these changes

2023-09-13 08:49 UTC, simmbiote approved these changes

2023-09-20 07:20 UTC, lezegom approved these changes

2023-09-20 09:04 UTC, merged